disp: msm: dp: Fix compilation issue with LTS 6.6.17
Below compilation issue is observed while moving to LTS 6.6.17.

dp_mst_drm.c:316:56: error: too many arguments to function call, \
						expected 2, have 3

Commit 4e042f022255 ("drm/dp_mst: Fix fractional DSC bpp handling")
updated DSC bpp handling, adopt to that to fix the build issue.

Signed-off-by: Satya Durga Srinivasu Prabhala <quic_satyap@quicinc.com>
Change-Id: I512cade949b84a173c1a42e28e1dbdb3721761c9